# Detection System Configuration

# Image Processing Parameters
image_processing:
  max_image_size: 2000
  resize_interpolation: "INTER_AREA"
  clahe_clip_limit: 3.0
  clahe_grid_size: [8, 8]

# OCR Parameters
ocr:
  languages: ["en"]
  batch_size: 4
  width_ths: 0.7
  height_ths: 0.7
  paragraph: false
  min_confidence: 0.3

# Symbol Detection Parameters
symbols:
  boundaries:
    color_range:
      lower: [40, 100, 100]
      upper: [80, 255, 255]
    min_area: 100
    line_length: 40
    max_gap: 20

  transport:
    color_range:
      lower: [0, 100, 100]
      upper: [10, 255, 255]
    min_length: 20
    max_gap: 15

  water_features:
    color_range:
      lower: [100, 100, 100]
      upper: [130, 255, 255]
    min_area: 300
    circularity_threshold: 0.5

  settlements:
    color_range:
      lower: [0, 0, 0]
      upper: [180, 50, 100]
    min_radius: 2
    max_radius: 20
    city_threshold: 12
    town_threshold: 7

# Text Detection Parameters
text:
  place_names:
    min_length: 2
    max_length: 50
    confidence_threshold: 0.3

  survey_numbers:
    min_value: 1
    max_value: 9999
    confidence_threshold: 0.4

# Training Parameters
training:
  epochs: 100
  batch_size: 32
  learning_rate: 0.001
  validation_split: 0.2
  early_stopping_patience: 10

# Validation Parameters
validation:
  iou_threshold: 0.5
  confidence_threshold: 0.3
  min_detection_size: 10
